apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-svc
  name: mysql-svc
spec:
  clusterIP: None
  selector:
    app: db-app
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
