apiVersion: v1
kind: Pod
metadata:
  name: random-crash
spec:
  containers:
    - name: app
      image: busybox
      command:
        - sh
        - '-c'
        - |
          WAIT=$((RANDOM % 30 + 10))
          echo "Running for $WAIT seconds..."
          sleep $WAIT

          if [ $((RANDOM % 2)) -eq 0 ]; then
            echo "Application crashed!"
            exit 1
          else
            echo "Application exited normally."
            exit 0
          fi
      resources: {}
      livenessProbe:
        exec:
          command:
            - sh
            - '-c'
            - exit $((RANDOM % 2))
        initialDelaySeconds: 5
        periodSeconds: 10
      readinessProbe:
        exec:
          command:
            - sh
            - '-c'
            - exit $((RANDOM % 2))
        initialDelaySeconds: 5
        periodSeconds: 10
  restartPolicy: Always

# kubectl run random-crash --image=busybox --dry-run=client -o yaml > app.yml